# Generated by Django 5.1.3 on 2024-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Никнейм пользователя'),
        ),
    ]
