# Generated by Django 5.1.3 on 2024-11-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5), ('SIX', 6), ('SEVEN', 7)], default='ONE', max_length=20, verbose_name='периодичность'),
        ),
    ]
