# Generated by Django 5.1.3 on 2024-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_date_alter_habit_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, max_length=30, null=True, verbose_name='Время выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения привычки'),
        ),
    ]
