# Generated by Django 5.1.3 on 2024-11-24 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='connected',
        ),
        migrations.AddField(
            model_name='habit',
            name='connected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit'),
        ),
    ]
